// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizJejX79p2Qkkm1IkHSBE9rrL0NDRFCU',
    appId: '1:256236669376:web:03cd3c3ef65cebfc6e6025',
    messagingSenderId: '256236669376',
    projectId: 'soscaasitech',
    authDomain: 'soscaasitech.firebaseapp.com',
    storageBucket: 'soscaasitech.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8qMeW5nbauSn-UDrqZibC8yZ-d6xPoZw',
    appId: '1:256236669376:android:150a6960001ccf276e6025',
    messagingSenderId: '256236669376',
    projectId: 'soscaasitech',
    storageBucket: 'soscaasitech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCstPED1jNlobiNQork0W6rsdG4mF8SbPE',
    appId: '1:256236669376:ios:36c1808125aa2fe46e6025',
    messagingSenderId: '256236669376',
    projectId: 'soscaasitech',
    storageBucket: 'soscaasitech.appspot.com',
    iosClientId: '256236669376-9rhpdd8u55t9ec9or73850jf0g7nt1ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCstPED1jNlobiNQork0W6rsdG4mF8SbPE',
    appId: '1:256236669376:ios:36c1808125aa2fe46e6025',
    messagingSenderId: '256236669376',
    projectId: 'soscaasitech',
    storageBucket: 'soscaasitech.appspot.com',
    iosClientId: '256236669376-9rhpdd8u55t9ec9or73850jf0g7nt1ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
